# Generated by Django 5.2.7 on 2026-03-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_user_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_registration',
            name='type',
            field=models.CharField(choices=[('admin', 'admin'), ('user', 'user')], default='user', max_length=20),
        ),
    ]
