# Generated by Django 5.2.7 on 2026-03-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_user_registration_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mens_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdt_name', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='pic')),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
