# Generated by Django 5.2.7 on 2026-03-26 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_mens_product_delete_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mens_product',
            new_name='product',
        ),
    ]
