# Generated by Django 5.2.7 on 2026-03-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_rename_mens_product_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('kids', 'Kids')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
